### ISSUE TITLE
KeyError: "region"

### ISSUE THREAD

**Issue by Rene1695** [ccmpbll/cloudflare-speedtest-mqtt#2]
Hi,

yesterday my internet provider was gone. Today everything is working again, but sadly I can not run any speedtest. In the log I got the following: 

![image](https://github.com/ccmpbll/cloudflare-speedtest-mqtt/assets/71972934/c21705fe-902b-48af-92ea-e91381c96fef)

It says data was send to MQTT server but I checked with MQTT Explorer and there is nothing.

I also tried reinstalling the docker but same result. Someone with the same issue? 

Best regards,
René

**Comment by ccmpbll** [comment]
@Rene1695 My apologies, but I am not able to replicate this issue. I have a couple of instances of this running and things seem to be fine. Just to be sure, I would remove and recreate the container.

**Comment by ccmpbll** [comment]
Woops... didn't mean to close this...

**Comment by Rene1695** [comment]
@ccmpbll thanks for checking! I will continue searching the issue in my system and closing the issue here :)
