### ISSUE TITLE
Upload speeds looks to off by a factor of 100

### ISSUE THREAD

**Issue by Mortalitis** [ccmpbll/cloudflare-speedtest-mqtt#3]
Issue looks to have started around 17:00 21.05.2024 (UK Time). No changes from my config in a long time on this setup. 

Running the speed test container on an unraid server and sending messages to my home assistant raspberry pi. Strangely the download speed is not affected at all and reports the data in the correct way, so right now I am not suspecting something I did is wrong. Suspect it might be a change on Cloudflare's end? 

I can confidently say my upload speeds should be in the region of 80Mbps not 8000Mbps. Running https://speed.cloudflare.com/ resulted in 484Mbps down and 70.3 up reported.

Home Assistant Graph
![image](https://github.com/ccmpbll/cloudflare-speedtest-mqtt/assets/9478401/c6f8d90c-47eb-4195-85b0-ef711f7aa2d0)

Topic capture in MQTT
![image](https://github.com/ccmpbll/cloudflare-speedtest-mqtt/assets/9478401/3a8bd45a-8fdb-4dc4-b3c6-5faebccc66b9)

Sensor setup in Home Assistant yaml
![image](https://github.com/ccmpbll/cloudflare-speedtest-mqtt/assets/9478401/98e7b559-ecc7-4cb4-911a-49bd1d4b5159)

**Comment by ccmpbll** [comment]
@Mortalitis I have resolved this issue. It should not have taken me this long to get to this. My apologies.
